refactor: tidy up and add alpine
Signed-off-by: Jakub Panek <me@panekj.dev>

diff --git a/get-deps b/get-deps
--- a/get-deps
+++ b/get-deps
@@ -1,100 +1,166 @@
-#!/bin/bash
+#!/bin/sh
 
-if ! bash ./ci/check-rust-version.sh ; then
-  exit 1
+case $1 in
+  --testing)
+    TESTING=0
+  ;;
+  '')
+    TESTING=1
+  ;;
+  *)
+    echo 'get-deps:'
+    echo '  --testing    include dependencies required for tests'
+    exit 1
+  ;;
+esac
+
+NOTFOUND=0
+
+test_cmd() {
+  command -v $1 >/dev/null
+}
+
+test_flag() {
+  test $TESTING -eq 0
+}
+
+if test -z "$SUDO"; then
+  if test_cmd 'sudo'; then
+    SUDO="sudo"
+  elif test_cmd 'doas'; then
+    SUDO="doas"
+  fi
 fi
 
-if test -z "${SUDO+x}" && hash sudo 2>/dev/null; then
-  SUDO="sudo"
-fi
+alpine_deps() {
+  APK="$SUDO apk"
+  $APK add \
+    'alpine-sdk' \
+    'bash' \
+    'build-base' \
+    'coreutils' \
+    'fontconfig-dev' \
+    'libssh2-dev' \
+    'libx11-dev' \
+    'libxkbcommon-dev' \
+    'openssl-dev' \
+    'pkgconf' \
+    'python3' \
+    'wayland-dev' \
+    'xcb-util-dev' \
+    'xcb-util-image-dev' \
+    'xcb-util-keysyms-dev' \
+    'xcb-util-wm-dev' \
+    'zlib-dev' \
+    'zstd-dev'
 
-# Centos may not have lsb_release installed (or even available at all)
-if test -e /etc/centos-release || test -e /etc/fedora-release; then
-  if test -x /bin/dnf ; then
+  if ! test_cmd 'cargo'; then
+    $APK add 'cargo'
+  fi
+
+  if test_flag; then
+    $APK add 'openssh'
+  fi
+}
+
+fedora_deps() {
+  if test_cmd 'dnf'; then
     YUM="$SUDO dnf"
-  else
+  elif test_cmd 'yum'; then
     YUM="$SUDO yum"
+  else
+    echo "No idea what package manager to use, sorry! (perhaps 'dnf' or 'yum' is not in \$PATH?)"
+    return 1
   fi
   # Fedora 33 moved some perl bits around
-  $YUM install -y perl-FindBin perl-File-Compare || true
+  $YUM install -y 'perl-FindBin' 'perl-File-Compare' || true
   $YUM install -y \
-    make \
-    gcc \
-    gcc-c++ \
-    fontconfig-devel \
-    openssl-devel \
-    perl-interpreter \
-    python3 \
-    libxcb-devel \
-    libxkbcommon-devel \
-    libxkbcommon-x11-devel \
-    wayland-devel \
-    mesa-libEGL-devel \
-    xcb-util-devel \
-    xcb-util-keysyms-devel \
-    xcb-util-image-devel \
-    xcb-util-wm-devel \
-    rpm-build
-  exit $?
-fi
+    'make' \
+    'gcc' \
+    'gcc-c++' \
+    'fontconfig-devel' \
+    'openssl-devel' \
+    'perl-interpreter' \
+    'python3' \
+    'libxcb-devel' \
+    'libxkbcommon-devel' \
+    'libxkbcommon-x11-devel' \
+    'wayland-devel' \
+    'mesa-libEGL-devel' \
+    'xcb-util-devel' \
+    'xcb-util-keysyms-devel' \
+    'xcb-util-image-devel' \
+    'xcb-util-wm-devel' \
+    'rpm-build'
 
-if test -x /usr/bin/lsb_release && test `lsb_release -si` = "openSUSE"; then
+  if test_flag; then
+    $YUM install -y 'openssh-server'
+  fi
+}
+
+suse_deps() {
   ZYPPER="$SUDO zypper"
-  $ZYPPER install -yl perl-FindBin perl-File-Compare || true
+  $ZYPPER install -yl 'perl-FindBin' 'perl-File-Compare' || true
   $ZYPPER install -yl \
-    make \
-    gcc \
-    gcc-c++ \
-    fontconfig-devel \
-    openssl-devel \
-    perl \
-    python3 \
-    libxcb-devel \
-    libxkbcommon-devel \
-    libxkbcommon-x11-devel \
-    wayland-devel \
-    Mesa-libEGL-devel \
-    xcb-util-devel \
-    xcb-util-keysyms-devel \
-    xcb-util-image-devel \
-    xcb-util-wm-devel \
-    rpm-build
-  exit $?
-fi
+    'make' \
+    'gcc' \
+    'gcc-c++' \
+    'fontconfig-devel' \
+    'openssl-devel' \
+    'perl' \
+    'python3' \
+    'libxcb-devel' \
+    'libxkbcommon-devel' \
+    'libxkbcommon-x11-devel' \
+    'wayland-devel' \
+    'Mesa-libEGL-devel' \
+    'xcb-util-devel' \
+    'xcb-util-keysyms-devel' \
+    'xcb-util-image-devel' \
+    'xcb-util-wm-devel' \
+    'rpm-build'
 
-if test -e /etc/debian_version ; then
+  if test_flag; then
+    $ZYPPER install -yl 'openssh-server'
+  fi
+}
+
+debian_deps() {
   APT="$SUDO apt-get"
-  apt-cache show libxcb-util-dev > /dev/null 2>&1 && XCBUTIL="libxcb-util-dev" || XCBUTIL="libxcb-util0-dev"
+  apt-cache show 'libxcb-util-dev' > /dev/null 2>&1 && XCBUTIL="libxcb-util-dev" || XCBUTIL="libxcb-util0-dev"
   $APT install -y \
-    bsdutils \
-    cmake \
-    dpkg-dev \
-    fakeroot \
-    gcc \
-    g++ \
-    libegl1-mesa-dev \
-    libssl-dev \
-    libfontconfig1-dev \
-    libwayland-dev \
-    libx11-xcb-dev \
-    libxcb-ewmh-dev \
-    libxcb-icccm4-dev \
-    libxcb-image0-dev \
-    libxcb-keysyms1-dev \
-    libxcb-randr0-dev \
-    libxcb-render0-dev \
-    libxcb-xkb-dev \
-    libxkbcommon-dev \
-    libxkbcommon-x11-dev \
+    'bsdutils' \
+    'cmake' \
+    'dpkg-dev' \
+    'fakeroot' \
+    'gcc' \
+    'g++' \
+    'libegl1-mesa-dev' \
+    'libssl-dev' \
+    'libfontconfig1-dev' \
+    'libwayland-dev' \
+    'libx11-xcb-dev' \
+    'libxcb-ewmh-dev' \
+    'libxcb-icccm4-dev' \
+    'libxcb-image0-dev' \
+    'libxcb-keysyms1-dev' \
+    'libxcb-randr0-dev' \
+    'libxcb-render0-dev' \
+    'libxcb-xkb-dev' \
+    'libxkbcommon-dev' \
+    'libxkbcommon-x11-dev' \
     "$XCBUTIL" \
-    lsb-release \
-    python3 \
-    xdg-utils \
-    xorg-dev
-  exit $?
-fi
+    'lsb-release' \
+    'python3' \
+    'xdg-utils' \
+    'xorg-dev'
 
-if test -e /etc/arch-release ; then
+  if test_flag; then
+    $APT install -y 'openssh-server'
+  fi
+}
+
+arch_deps() {
   PACMAN="$SUDO pacman"
   $PACMAN -S --noconfirm --needed \
     'base-devel' \
@@ -113,10 +179,45 @@ if test -e /etc/arch-release ; then
     'xcb-util-image' \
     'xcb-util-keysyms' \
     'xcb-util-wm'
-  exit $?
-fi
 
-if test -e /etc/gentoo-release ; then
+  if test_cmd; then
+    $PACMAN -S --noconfirm --needed \
+      'openssh-server'
+  fi
+}
+
+bsd_deps() {
+  PKG="$SUDO pkg"
+  $PKG install -y \
+    'cmake' \
+    'curl' \
+    'egl-wayland' \
+    'expat' \
+    'fontconfig' \
+    'gcc' \
+    'gettext' \
+    'git' \
+    'gmake' \
+    'libxcb' \
+    'libxkbcommon' \
+    'mesa-devel' \
+    'openssl' \
+    'p5-ExtUtils-MakeMaker' \
+    'perl5' \
+    'pkgconf' \
+    'python3' \
+    'rust' \
+    'wayland' \
+    'libxcb' \
+    'xcb-util' \
+    'xcb-util-image' \
+    'xcb-util-keysyms' \
+    'xcb-util-wm' \
+    'z' \
+    'zip'
+}
+
+gentoo_deps() {
   portageq envvar USE | xargs -n 1 | grep '^X$' \
   || (echo 'X is not found in USE flags' && exit 1)
   EMERGE="$SUDO emerge"
@@ -136,48 +237,100 @@ if test -e /etc/gentoo-release ; then
     'xcb-util-image' \
     'xcb-util-keysyms' \
     'xcb-util-wm'
-  exit $?
+}
+
+fallback_method() {
+  if test -e /etc/alpine-release; then
+    alpine_deps
+  elif test -e /etc/centos-release || test -e /etc/fedora-release || test -e /etc/redhat-release; then
+    fedora_deps
+  elif test -e /etc/debian_version; then
+    debian_deps
+  elif test -e /etc/arch-release; then
+    arch_deps
+  elif test -e /etc/gentoo-release; then
+    gentoo_deps
+  elif test_cmd 'lsb_release' && test "$(lsb_release -si)" = "openSUSE"; then
+    suse_deps
+  fi
+
+  # OSTYPE is set by bash
+  case $OSTYPE in
+    darwin*|msys)
+      echo "skipping darwin*/msys"
+    ;;
+    freebsd*)
+      bsd_deps
+    ;;
+    ''|linux-gnu)
+      # catch and known OSTYPE
+      echo "\$OSTYPE is '$OSTYPE'"
+    ;;
+    *)
+      NOTFOUND=1
+      return 1
+    ;;
+  esac
+  return 0
+}
+
+if test -e /etc/os-release; then
+  . /etc/os-release
 fi
 
-case $OSTYPE in
-  darwin*|msys)
-    exit 0
+case $ID in
+  centos|fedora|rhel)
+    fedora_deps
   ;;
-  freebsd*)
-    PKG="$SUDO pkg"
-    $PKG install -y \
-      cmake \
-      curl \
-      egl-wayland \
-      expat \
-      fontconfig \
-      gcc \
-      gettext \
-      git \
-      gmake \
-      libxcb \
-      libxkbcommon \
-      mesa-devel \
-      openssl \
-      p5-ExtUtils-MakeMaker \
-      perl5 \
-      pkgconf \
-      python3 \
-      rust \
-      wayland \
-      libxcb \
-      xcb-util \
-      xcb-util-image \
-      xcb-util-keysyms \
-      xcb-util-wm \
-      z \
-      zip
-    exit $?
-    ;;
+  alpine)
+    alpine_deps
+  ;;
+  *suse*)
+    suse_deps
+  ;;
+  debian|ubuntu)
+    debian_deps
+  ;;
+  freebsd) # available since 13.0
+    bsd_deps
+  ;;
+  arch)
+    arch_deps
+  ;;
+  gentoo)
+    gentoo_deps
+  ;;
   *)
-    echo "Please contribute the commands to install the deps"
-    echo "For `lsb_release -ds`"
-    cat /etc/os-release
-    exit 1
+    echo "Couldn't find OS by ID, found ID: $ID"
+    echo "Fallback to detecting '/etc/<name>-release'"
+    fallback_method
+    if ! test $? -eq 0; then
+      if ! test $NOTFOUND -eq 0; then
+        echo "Couldn't identify OS through '/etc/<name>-release'"
+      fi
+      exit 1
+    fi
   ;;
 esac
+
+if ! test $NOTFOUND -eq 0; then
+  echo "Please contribute the commands to install the deps for:"
+  if test_cmd 'lsb_release'; then
+    lsb_release -ds
+  elif test -e /etc/os-release; then
+    cat /etc/os-release
+  else
+    echo "Couldn't recognise system"
+  fi
+  exit 1
+fi
+
+if ! test_cmd 'rustc'; then
+  echo "Rust is not installed!"
+  echo "Please see https://wezfurlong.org/wezterm/install/source.html for installation instructions"
+  exit 1
+fi
+
+if ! ./ci/check-rust-version.sh; then
+  exit 1
+fi
