ci: bleh, do retry inline as part of upload

diff --git a/.github/workflows/gen_debian11_continuous.yml b/.github/workflows/gen_debian11_continuous.yml
--- a/.github/workflows/gen_debian11_continuous.yml
+++ b/.github/workflows/gen_debian11_continuous.yml
@@ -158,4 +158,22 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         shell: bash
-        run: "bash ci/retry.sh gh release upload --clobber nightly wezterm-*.deb wezterm-*.xz"
+        run: |
+
+          set -x
+          set -e
+
+          max_attempts=4
+          attempt=1
+
+          until gh release upload --clobber nightly wezterm-*.deb wezterm-*.xz
+          do
+            if (( attempt == max_attempts ))
+            then
+              echo "Failed after $max_attempts attempts"
+              exit 1
+            fi
+
+            sleep 5
+            : $(( attempt++ ))
+          done
diff --git a/.github/workflows/gen_fedora35_continuous.yml b/.github/workflows/gen_fedora35_continuous.yml
--- a/.github/workflows/gen_fedora35_continuous.yml
+++ b/.github/workflows/gen_fedora35_continuous.yml
@@ -131,4 +131,22 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         shell: bash
-        run: "bash ci/retry.sh gh release upload --clobber nightly wezterm-*.rpm"
+        run: |
+
+          set -x
+          set -e
+
+          max_attempts=4
+          attempt=1
+
+          until gh release upload --clobber nightly wezterm-*.rpm
+          do
+            if (( attempt == max_attempts ))
+            then
+              echo "Failed after $max_attempts attempts"
+              exit 1
+            fi
+
+            sleep 5
+            : $(( attempt++ ))
+          done
diff --git a/.github/workflows/gen_ubuntu18_continuous.yml b/.github/workflows/gen_ubuntu18_continuous.yml
--- a/.github/workflows/gen_ubuntu18_continuous.yml
+++ b/.github/workflows/gen_ubuntu18_continuous.yml
@@ -116,4 +116,22 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         shell: bash
-        run: "bash ci/retry.sh gh release upload --clobber nightly wezterm-*.deb wezterm-*.xz *src.tar.gz *.AppImage *.zsync"
+        run: |
+
+          set -x
+          set -e
+
+          max_attempts=4
+          attempt=1
+
+          until gh release upload --clobber nightly wezterm-*.deb wezterm-*.xz *src.tar.gz *.AppImage *.zsync
+          do
+            if (( attempt == max_attempts ))
+            then
+              echo "Failed after $max_attempts attempts"
+              exit 1
+            fi
+
+            sleep 5
+            : $(( attempt++ ))
+          done
diff --git a/.github/workflows/gen_windows_continuous.yml b/.github/workflows/gen_windows_continuous.yml
--- a/.github/workflows/gen_windows_continuous.yml
+++ b/.github/workflows/gen_windows_continuous.yml
@@ -90,4 +90,22 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         shell: bash
-        run: "bash ci/retry.sh gh release upload --clobber nightly WezTerm-*.zip WezTerm-*.exe"
+        run: |
+
+          set -x
+          set -e
+
+          max_attempts=4
+          attempt=1
+
+          until gh release upload --clobber nightly WezTerm-*.zip WezTerm-*.exe
+          do
+            if (( attempt == max_attempts ))
+            then
+              echo "Failed after $max_attempts attempts"
+              exit 1
+            fi
+
+            sleep 5
+            : $(( attempt++ ))
+          done
